title: Emerging Technologies
author: Jon

domain: jdw-20.github.io
url: "https://jdw-20.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima

header_pages:
  - none.md

minima:
  skin: auto

plugins:
  - jekyll-feed
