---
layout: post
title: Fabrication 2
categories: assignment cad function
share: "true"
published: "true"
image: "/assets/images/thumbnails/fab2.jpg"
excerpt: ""
---

![image](/assets/images/print/rod.png)
![image](/assets/images/print/end1.png)
![image](/assets/images/print/end2.png)
![image](/assets/images/print/end3.png)
![image](/assets/images/print/end4.png)

I made this in freecad because I actually kind of don't hate it.  I found myself getting more frustrated at fusion than I did freecad. I made measurements of everything I thought was relevant: the length of the rings on the notebook, the diameter of the rings, and the length of the point of a pushpin. Unfortunately I do not own calipers, so I found the diameter I would need by putting something in that fits well and using string and a ruler to get the circumference, then solved for d. The most I struggled on this was when I was trying to use the mirror tool to make both sides of the end piece the same. At the start of the project I put the sketch with a corner at the origin, and so flipping across the origin didn't actually do anything. I had to go back and find a way to reference the center of the sketch to the X axis. Freecad also crashed a lot when I did certain things. I beveled many of the edges so they wouldn't be as sharp. Freecad apparently didn't like reckoning this with doing any actions to the mesh after. I think after this class I have gotten comfortable enough with CAD software, and maybe I will use it to make other parts.

The diameter of the rod that can fit through the rings is 9 mm. The size of the cube that makes up the end piece is somewhat arbitrary, the x and y being 3 cm. The Z however is 15 mm to give some space on either side of the rod.
I then had to use holes to make the faces that have the push pins to be less than 5 mm which is the length of the pin part. I made it 3 mm so that the pin has some space to go into the cork board.
The pen holder sticks out 3 mm and has a 2 mm hole, leaving a 1 mm piece for the pen clip to hook on to.
The rod piece is 9 mm and 5 cm long.

